/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UzrxpgVEsxU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Toaster } from "@/components/ui/toaster"
import { Badge } from "@/components/ui/badge"
import { useToast } from "@/components/ui/use-toast"
import { track } from "./analytics"
import { LanguageSwitch, useLanguage } from "./language-provider"
import { SettingsDialog } from "./settings-dialog"
import { useSettings } from "./settings-provider"
import { Settings as SettingsIcon, X } from "lucide-react"
import { useEffect, useRef, useState } from "react"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"

function getLastPartOfUrl(url){
  // remove params and hash and trailing slash
  url = url.replace(/(\?.*)|(#.*)|\/$/, "")
  const parts = url.split("/")
  // convert to filename safe string
  const last = parts[parts.length - 1].replace(/[^a-z0-9]/gi, '_').toLowerCase()
  return last
}

// 下载 Markdown 文件。
// 用 Blob 而非 data: URL —— data: URL 会被 encodeURIComponent 撑爆长度上限，
// 长文会被截断，文件也随之损坏。同时在开头写入 UTF-8 BOM（\uFEFF），
// 让 Windows 记事本 / 浏览器明确按 UTF-8 解码，避免中文显示为乱码。
function downloadMarkdownFile(text, filename){
  const blob = new Blob(["\uFEFF", text], { type: "text/markdown;charset=utf-8" })
  const objectUrl = window.URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = objectUrl
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  window.URL.revokeObjectURL(objectUrl)
}

// 问号帮助气泡：桌面端 hover 显示，触屏端点击开关（点外部关闭）。
// 用 pointerType 区分鼠标与触摸，避免触摸的伪 hover 事件把气泡瞬间关掉。
function HelpTooltip({children}){
  const [open, setOpen] = useState(false)
  const wrapRef = useRef(null)

  useEffect(() => {
    if (!open) return
    function onDocPointerDown(e){
      if (wrapRef.current && !wrapRef.current.contains(e.target)) setOpen(false)
    }
    document.addEventListener("pointerdown", onDocPointerDown)
    return () => document.removeEventListener("pointerdown", onDocPointerDown)
  }, [open])

  return (
    <span ref={wrapRef} className="relative inline-flex ml-2 align-middle">
      <Button
        type="button"
        variant="ghost"
        aria-label="帮助"
        className="ml-0 h-6 w-6 rounded-full p-0"
        onPointerEnter={(e) => { if (e.pointerType === "mouse") setOpen(true) }}
        onPointerLeave={(e) => { if (e.pointerType === "mouse") setOpen(false) }}
        onClick={() => setOpen(o => !o)}
      >
        <Badge variant="outline">?</Badge>
      </Button>
      {open && (
        <span
          role="tooltip"
          onClick={(e) => e.stopPropagation()}
          className="absolute left-1/2 top-full z-50 mt-2 w-64 max-w-[80vw] -translate-x-1/2 break-words rounded-md border border-gray-200 bg-white p-3 text-xs leading-relaxed text-gray-700 shadow-lg sm:w-72 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200"
        >
          {children}
        </span>
      )}
    </span>
  )
}
export function Homepage() {
  const { toast } = useToast()
  const { t } = useLanguage()
  const { apiKey, baseUrl, model, hasKey } = useSettings()
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [url, setUrl] = useState("");
  // 粘贴网页内容 / 上传本地网页文件：手机上无法装书签时的兜底方案
  const [pasteMode, setPasteMode] = useState(false);
  const [pastedHtml, setPastedHtml] = useState("");
  const [fileName, setFileName] = useState("");
  const [imagesDir, setImagesDir] = useState("images");
  const [downloadImages, setDownloadImages] = useState(false);
  const [removeNonContent, setRemoveNonContent] = useState(true);
  const [imagesBasePathOverride, SetImagesBasePathOverride] = useState(undefined);
  const [isLoading, setIsLoading] = useState(false);
  const [gptEnabled, setGptEnabled] = useState(false);
  const [applyGpt, setApplyGpt] = useState("");
  const [bigModel, setBigModel] = useState(false);

  const [md, setMd] = useState("");

  function saveSettingsToLocalStorage(){
    const settings = {
      url,
      imagesDir,
      downloadImages,
      imagesBasePathOverride,
      removeNonContent,
      applyGpt,
      bigModel,
    }
    localStorage.setItem("settings", JSON.stringify(settings))
  }

  useEffect(()=>{
    track("Homepage Loaded")
    const settings = localStorage.getItem("settings");
    if (settings){
      const parsed = JSON.parse(settings);
      setUrl(parsed.url || "")
      setApplyGpt(parsed.applyGpt || "")
      if (parsed.applyGpt) setGptEnabled(true)
      setRemoveNonContent(!!parsed.removeNonContent)
      setBigModel(!!parsed.bigModel)
      setImagesDir(parsed.imagesDir)
      setDownloadImages(!!parsed.downloadImages)
      SetImagesBasePathOverride(parsed.imagesBasePathOverride)
    }
  }, [])

  async function submit(){
    if (isLoading){
      return;
    }
    if (!url){
      return toast({
        title: t("invalidUrlTitle"),
        description: t("invalidUrlDesc"),
      })
    }
    // const fullUrl = `/api/tomd?url=${url}&downloadImages=${downloadImages}&imagesDir=${imagesDir}&imagesBasePathOverride=${imagesBasePathOverride}&removeNonContent=${removeNonContent}`
    const payload = {
      url,
      downloadImages,
      imagesDir,
      imagesBasePathOverride,
      removeNonContent,
      applyGpt,
      bigModel,
    }

    // 用了 AI 处理却没填密钥，直接拦下来，别浪费一次转换
    if (gptEnabled && applyGpt && !hasKey){
      return toast({
        title: t("needApiKeyTitle"),
        description: t("needApiKeyDesc"),
      })
    }

    track("Convert Clicked", payload)

    // 密钥只在这次请求里随请求头传给服务端，不会存到服务器
    const headers = { "Content-Type": "application/json" }
    if (apiKey) headers["x-api-key"] = apiKey
    if (baseUrl) headers["x-base-url"] = baseUrl
    if (model) headers["x-model"] = model

    setIsLoading(true)
    const resp = await fetch("/api/tomd", {
      method: "POST",
      headers,
      body: JSON.stringify(payload)
    });
    // const resp = await fetch(fullUrl)
    if (!resp.ok){
      // 把服务端返回的具体原因（如反爬验证页提示）显示出来，而不是笼统的「转换失败」
      let reason = t("failedDesc");
      try {
        const txt = await resp.text();
        if (txt) reason = txt;
      } catch (e) { /* ignore */ }
      toast({
        title: t("failedTitle"),
        description: reason,
      })
      track("Download Failed", payload)
      // 自动降级：服务端抓不到（反爬 / SPA）时，直接帮用户切到「粘贴网页内容」模式，
      // 省得他自己判断该用哪种方式。判定依据：错误信息里的关键词。
      const r = String(reason || "");
      const blocked = /403|521|503|拒绝|反爬|安全验证|人机|验证/i.test(r);
      const tooLittle = /正文太少|JS 渲染|SPA/i.test(r);
      if (blocked || tooLittle){
        setPasteMode(true);
        toast({
          title: t("fallbackTitle"),
          description: blocked ? t("fallbackBlockedDesc") : t("fallbackSpaDesc"),
        });
      }
    }
    if (resp.ok && !downloadImages){
      const md = await resp.text();
      toast({
        title: t("successTitle"),
        description: t("successDesc"),
      })
      downloadMarkdownFile(md, `${getLastPartOfUrl(url) || "markdown"}.md`);
      track("Downloaded Markdown", {withImages: false})

    } 
    else if (resp.ok && downloadImages){
      const blob = await resp.blob();
      const objectUrl = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = objectUrl;
      a.download = `${getLastPartOfUrl(url)}.zip` || "markdd.zip";
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(objectUrl);
      toast({
        title: t("downloadStartedTitle"),
        description: t("downloadStartedDesc"),
      })
      track("Downloaded Markdown", {withImages: true})
    }
    saveSettingsToLocalStorage()
    setIsLoading(false)
  }

  // 粘贴模式提交：把用户在文章页复制的正文/HTML 直接转成 Markdown（无需书签、无需 Cookie）
  async function submitPasted(){
    if (isLoading) return;
    const raw = (pastedHtml || "").trim();
    if (!raw){
      return toast({ title: t("pasteEmptyTitle"), description: t("pasteEmptyDesc") });
    }
    const looksHtml = /<[a-z][\s\S]*>/i.test(raw);
    const html = looksHtml
      ? raw
      : `<!doctype html><html><head><meta charset="utf-8"></head><body><pre>${raw.replace(/&/g,"&amp;").replace(/</g,"&lt;")}</pre></body></html>`;
    track("Convert Pasted", {});
    setIsLoading(true);
    try {
      const resp = await fetch("/api/fromhtml", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ html, url, removeNonContent }),
      });
      if (!resp.ok){
        let reason = t("failedDesc");
        try { const txt = await resp.text(); if (txt) reason = txt; } catch (e) { /* ignore */ }
        toast({ title: t("failedTitle"), description: reason });
      } else {
        const md = await resp.text();
        toast({ title: t("successTitle"), description: t("successDesc") });
        downloadMarkdownFile(md, `${getLastPartOfUrl(url) || "markdown"}.md`);
        track("Downloaded Markdown", { pasted: true });
      }
    } catch (e) {
      toast({ title: t("failedTitle"), description: String(e && e.message || e) });
    } finally {
      setIsLoading(false);
    }
  }

  return (
    // 用 my-auto 做垂直居中（而不是 items-center）：内容比屏幕高时不会把顶部挤出可视区
    (<main className="safe-bottom relative flex min-h-[100dvh] w-full justify-center px-4 pb-12 pt-16 sm:px-6 sm:pb-16 sm:pt-14 lg:px-8">
      <Toaster />
      <div className="safe-top-right absolute right-3 top-3 z-10 flex items-center gap-1.5 sm:right-6 sm:top-6">
        <button
          type="button"
          onClick={() => setSettingsOpen(true)}
          title={t("settingsTitle")}
          aria-label={t("settingsTitle")}
          className={
            "flex h-9 w-9 items-center justify-center rounded-full border border-gray-200 bg-white/80 shadow-sm backdrop-blur transition-colors hover:bg-gray-100 sm:h-8 sm:w-8 dark:border-gray-700 dark:bg-gray-900/70 dark:hover:bg-gray-800 " +
            (hasKey ? "text-orange-500" : "text-gray-500")
          }>
          <SettingsIcon className="h-4 w-4 sm:h-3.5 sm:w-3.5" />
        </button>
        <LanguageSwitch />
      </div>
      <SettingsDialog open={settingsOpen} onClose={() => setSettingsOpen(false)} />
      <div className="my-auto flex w-full flex-col items-center">
        <div className="mb-8 space-y-2.5 text-center sm:mb-12 sm:space-y-3">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl">📥<br/>Markdown<b>Down</b></h1>
          <p
            className="mx-auto max-w-[560px] text-sm leading-relaxed text-gray-500 dark:text-gray-400 sm:text-base">
            {t("subtitle")}<br/> {t("subtitle2")}
          </p>
        </div>
        <div className="w-full max-w-md space-y-4 sm:max-w-xl sm:space-y-6 lg:max-w-2xl">
          <div className="flex w-full flex-col gap-2.5 sm:flex-row sm:items-center sm:gap-3">
            <div className="relative flex-1">
              <Input id="md-src-url" value={url} type="text" placeholder={t("urlPlaceholder")} className={`h-12 pr-9 text-base sm:h-11 sm:text-sm`} onChange={val=>setUrl(val.target.value)} onKeyDown={(e)=>{
                if (e.key === "Enter"){
                  submit()
                }
              }} />
              {url && (
                <button
                  type="button"
                  aria-label={t("clearInput")}
                  title={t("clearInput")}
                  onClick={() => setUrl("")}
                  className="absolute right-2.5 top-1/2 -translate-y-1/2 flex h-7 w-7 items-center justify-center rounded-full text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-600 sm:h-5 sm:w-5 dark:hover:bg-gray-800 dark:hover:text-gray-200"
                >
                  <X className="h-4 w-4 sm:h-3.5 sm:w-3.5" />
                </button>
              )}
            </div>
            <Button disabled={isLoading} type="submit" onClick={submit} className="h-12 w-full px-6 text-base sm:h-11 sm:w-auto sm:text-sm">
              {isLoading ? t("converting") : t("convert")}
            </Button>
          </div>
          {pasteMode && (
            <p className="text-xs leading-relaxed text-gray-500 dark:text-gray-400 sm:text-sm">
              {t("pasteModeNote")}
            </p>
          )}          
          <div className="flex flex-col gap-4 sm:gap-6">
            <Card className="shadow-sm">
              <CardHeader className="space-y-1 p-4 pb-2.5 sm:p-6 sm:pb-3">
                <CardTitle className="text-sm font-semibold sm:text-base">{t("options")}</CardTitle>
              </CardHeader>
              <CardContent className="p-4 pt-0 sm:p-6 sm:pt-0">
              <div className="flex flex-col gap-3.5 sm:grid sm:grid-cols-2 sm:gap-x-8 sm:gap-y-4">
              <div className="flex items-center gap-2.5">
              <Checkbox id="remove-noncontent" className="h-5 w-5 sm:h-4 sm:w-4" checked={removeNonContent} onClick={t=>setRemoveNonContent(!removeNonContent)} />
              <label className="text-sm leading-snug sm:text-[15px]" htmlFor="remove-noncontent">
                {t("removeNonContent")}
                <HelpTooltip>
                  {t("removeNonContentHelp")}
                </HelpTooltip>
              </label>
            </div>
            <div className="flex items-center gap-2.5">
              <Checkbox id="remove-images" className="h-5 w-5 sm:h-4 sm:w-4" checked={downloadImages} onClick={t=>setDownloadImages(!downloadImages)} />
              <label className="text-sm leading-snug sm:text-[15px]" htmlFor="remove-images">
                {t("downloadImages")}
                <HelpTooltip>
                  {t("downloadImagesHelp")}
                </HelpTooltip>
              </label>
            </div>
            <div className="flex items-center gap-2.5">
            <Checkbox id="apply-gpt" className="h-5 w-5 sm:h-4 sm:w-4" checked={gptEnabled} onClick={t=>{
              const newValue = !gptEnabled;
              if (!newValue){
                setApplyGpt("")
              }
              setGptEnabled(newValue);
              }} />
              <Label className="text-sm leading-snug sm:text-[15px]" htmlFor="apply-gpt">
                {t("applyGpt")}
                <HelpTooltip>
                  {t("applyGptHelp")}
                </HelpTooltip>
              </Label>
            </div>
            <div className="flex items-center gap-2.5">
              <Checkbox id="paste-mode" className="h-5 w-5 sm:h-4 sm:w-4" checked={pasteMode} onClick={()=>setPasteMode(!pasteMode)} />
              <Label className="text-sm leading-snug sm:text-[15px]" htmlFor="paste-mode">
                {t("pasteMode")}
                <HelpTooltip>
                  {t("pasteModeHelp")}
                </HelpTooltip>
              </Label>
            </div>
              </div>
              </CardContent>
            </Card>

            {pasteMode && (
              <Card className="shadow-sm">
                <CardHeader className="space-y-1 p-4 pb-2.5 sm:p-6 sm:pb-3">
                  <CardTitle className="text-sm font-semibold sm:text-base">{t("pasteCardTitle")}</CardTitle>
                </CardHeader>
                <CardContent className="p-4 pt-0 sm:p-6 sm:pt-0">
                  <p className="mb-4 text-sm leading-relaxed text-gray-600 dark:text-gray-300 sm:text-[15px]">
                    {t("pasteCardDesc")}
                  </p>
                  {/* 上传本地网页文件：手机浏览器"保存网页"后选文件即可，最稳、不依赖书签 */}
                  <div className="mb-4">
                    <label className="mb-1.5 block text-sm leading-none">
                      {t("uploadHtmlLabel")}
                    </label>
                    <input
                      id="html-file"
                      type="file"
                      accept=".html,.htm,.txt,text/html,text/plain"
                      className="block w-full py-1 text-sm text-gray-600 dark:text-gray-300 file:mr-3 file:rounded-md file:border-0 file:bg-zinc-900 file:px-3 file:py-2 file:text-sm file:font-medium file:text-white hover:file:bg-zinc-700 dark:file:bg-zinc-100 dark:file:text-zinc-900"
                      onChange={async (e)=>{
                        const f = e.target.files && e.target.files[0];
                        if (!f) return;
                        try {
                          const text = await f.text();
                          setPastedHtml(text);
                          setFileName(f.name || "");
                          toast({ title: t("fileLoadedTitle"), description: (f.name || "") + " · " + text.length + " 字" });
                        } catch (err) {
                          toast({ title: t("failedTitle"), description: String(err && err.message || err) });
                        }
                      }}
                    />
                    {fileName && (
                      <p className="text-xs text-gray-500 dark:text-gray-400 mt-1 break-all">
                        {t("fileLoadedHint")}{fileName}
                      </p>
                    )}
                  </div>
                  <Textarea
                    id="pasted-html"
                    className="min-h-[9rem] font-mono text-xs sm:min-h-[12rem] sm:text-sm"
                    placeholder={t("pastePlaceholder")}
                    value={pastedHtml}
                    onChange={val=>setPastedHtml(val.target.value)}
                  />
                  <div className="mt-4 flex flex-col gap-2.5 sm:flex-row sm:items-center sm:gap-3">
                    <Input value={url} type="text" placeholder={`${t("urlPlaceholder")}（可选）`} className="h-12 text-base sm:h-11 sm:text-sm" onChange={val=>setUrl(val.target.value)} />
                    <Button disabled={isLoading} type="button" onClick={submitPasted} className="h-12 w-full px-6 text-base sm:h-11 sm:w-auto sm:text-sm">
                      {isLoading ? t("converting") : t("convert")}
                    </Button>
                  </div>
                </CardContent>
              </Card>
            )}
            {downloadImages && (
              <Card className="shadow-sm">
              <CardHeader className="space-y-1 p-4 pb-2.5 sm:p-6 sm:pb-3">
                <CardTitle className="text-sm font-semibold sm:text-base">{t("imageOptions")}</CardTitle>
              </CardHeader>
              <CardContent className="p-4 pt-0 sm:p-6 sm:pt-0">
              <div className="grid gap-4 sm:grid-cols-2 sm:gap-6">
              <div className="space-y-2">
              <Label className="text-sm leading-snug" htmlFor="images-folder">
                {t("overrideImagesFolder")}
                <HelpTooltip>
                  {t("overrideImagesFolderHelp")}
                </HelpTooltip>
              </Label>
              <Input id="images-folder" placeholder={t("enterFolderName")} type="text" value={imagesDir} className="h-12 text-base sm:h-11 sm:text-sm" onChange={val=>{
                setImagesDir(val.target.value)
              }} />
              
            </div>
            <div className="space-y-2">
              <Label className="text-sm leading-snug" htmlFor="images-basepath">
                {t("overrideBasePath")}
                <HelpTooltip>
                  {t("overrideBasePathHelp")}
                </HelpTooltip>
              </Label>
              <Input id="images-basepath" placeholder={`./${imagesDir}`} type="text" value={imagesBasePathOverride} className="h-12 text-base sm:h-11 sm:text-sm" onChange={val=>{
                SetImagesBasePathOverride(val.target.value)
              }} />
              </div>
              </div>
              </CardContent>
            </Card>
            )}
 {gptEnabled && <Card className="shadow-sm">
              <CardHeader className="space-y-1 p-4 pb-2.5 sm:p-6 sm:pb-3">
                <CardTitle className="text-sm font-semibold sm:text-base">{t("gptOptions")}</CardTitle>
              </CardHeader>
              <CardContent className="p-4 pt-0 sm:p-6 sm:pt-0">
            <div className="space-y-4">
                <div className="flex items-center gap-2.5">
                <Checkbox id="big-model" className="h-5 w-5 sm:h-4 sm:w-4" checked={bigModel} onClick={t=>setBigModel(!bigModel)} />
                <label className="text-sm leading-snug sm:text-[15px]" htmlFor="big-model">
                  {t("useGpt4")}
                </label>
              </div>
              <Textarea id="apply-gpt-txt" 
              className="min-h-[12rem] text-base sm:min-h-[18rem] sm:text-sm"
              placeholder={t("gptPlaceholder")} value={applyGpt} onChange={val=>{ 
                setApplyGpt(val.target.value)
              }} />
            </div>
            </CardContent>
            </Card>}
            
          </div>
          
        </div>
        <footer className="mt-10 text-[11px] text-gray-500 dark:text-gray-400 sm:mt-14 sm:text-xs">
          <p>
          © {new Date().getFullYear()}&nbsp;
            <a className="underline" href="https://github.com/ZhuangRenyang" target="_blank" rel="noopener noreferrer">
              ZhuangRenyang
            </a>
          </p>
        </footer>
      </div>
      
    </main>)
  );
}
