/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UzrxpgVEsxU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Toaster } from "@/components/ui/toaster"
import { Badge } from "@/components/ui/badge"
import { useToast } from "@/components/ui/use-toast"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
 import { track } from "./analytics"
import { LanguageSwitch, useLanguage } from "./language-provider"
import { SettingsDialog } from "./settings-dialog"
import { useSettings } from "./settings-provider"
import { Settings as SettingsIcon } from "lucide-react"
import { useEffect, useState } from "react"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"

function getLastPartOfUrl(url){
  // remove params and hash and trailing slash
  url = url.replace(/(\?.*)|(#.*)|\/$/, "")
  const parts = url.split("/")
  // convert to filename safe string
  const last = parts[parts.length - 1].replace(/[^a-z0-9]/gi, '_').toLowerCase()
  return last
}


function HelpTooltip({children}){
  return (
    <TooltipProvider delayDuration={10}>
      <Tooltip>
        <TooltipTrigger asChild>
          <Button className="ml-2" variant="ghost" size="ghost"><Badge variant="outline">?</Badge></Button>
        </TooltipTrigger>
        <TooltipContent>
          <p>{children}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}
export function Homepage() {
  const { toast } = useToast()
  const { t } = useLanguage()
  const { apiKey, baseUrl, model, hasKey } = useSettings()
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [url, setUrl] = useState("");
  const [imagesDir, setImagesDir] = useState("images");
  const [downloadImages, setDownloadImages] = useState(false);
  const [removeNonContent, setRemoveNonContent] = useState(true);
  const [imagesBasePathOverride, SetImagesBasePathOverride] = useState(undefined);
  const [isLoading, setIsLoading] = useState(false);
  const [gptEnabled, setGptEnabled] = useState(false);
  const [applyGpt, setApplyGpt] = useState("");
  const [bigModel, setBigModel] = useState(false);

  const [md, setMd] = useState("");

  function saveSettingsToLocalStorage(){
    const settings = {
      url,
      imagesDir,
      downloadImages,
      imagesBasePathOverride,
      removeNonContent,
      applyGpt,
      bigModel
    }
    localStorage.setItem("settings", JSON.stringify(settings))
  }

  useEffect(()=>{
    track("Homepage Loaded")
    const settings = localStorage.getItem("settings");
    if (settings){
      const parsed = JSON.parse(settings);
      setUrl(parsed.url || "")
      setApplyGpt(parsed.applyGpt || "")
      if (parsed.applyGpt) setGptEnabled(true)
      setRemoveNonContent(!!parsed.removeNonContent)
      setBigModel(!!parsed.bigModel)
      setImagesDir(parsed.imagesDir)
      setDownloadImages(!!parsed.downloadImages)
      SetImagesBasePathOverride(parsed.imagesBasePathOverride)
    }
  }, [])

  async function submit(){
    if (isLoading){
      return;
    }
    if (!url){
      return toast({
        title: t("invalidUrlTitle"),
        description: t("invalidUrlDesc"),
      })
    }
    // const fullUrl = `/api/tomd?url=${url}&downloadImages=${downloadImages}&imagesDir=${imagesDir}&imagesBasePathOverride=${imagesBasePathOverride}&removeNonContent=${removeNonContent}`
    const payload = {
      url,
      downloadImages,
      imagesDir,
      imagesBasePathOverride,
      removeNonContent,
      applyGpt,
      bigModel
    }

    // 用了 AI 处理却没填密钥，直接拦下来，别浪费一次转换
    if (gptEnabled && applyGpt && !hasKey){
      return toast({
        title: t("needApiKeyTitle"),
        description: t("needApiKeyDesc"),
      })
    }

    track("Convert Clicked", payload)

    // 密钥只在这次请求里随请求头传给服务端，不会存到服务器
    const headers = { "Content-Type": "application/json" }
    if (apiKey) headers["x-api-key"] = apiKey
    if (baseUrl) headers["x-base-url"] = baseUrl
    if (model) headers["x-model"] = model

    setIsLoading(true)
    const resp = await fetch("/api/tomd", {
      method: "POST",
      headers,
      body: JSON.stringify(payload)
    });
    // const resp = await fetch(fullUrl)
    if (!resp.ok){
      toast({
        title: t("failedTitle"),
        description: t("failedDesc"),
      })
      track("Download Failed", payload)
    }
    if (resp.ok && !downloadImages){
      const md = await resp.text();
      toast({
        title: t("successTitle"),
        description: t("successDesc"),
      })
      const a = document.createElement('a');
      a.href = `data:text/plain;charset=utf-8,${encodeURIComponent(md)}`;
      a.download = `${getLastPartOfUrl(url)}.md` || "markdd.md";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      track("Downloaded Markdown", {withImages: false})

    } 
    else if (resp.ok && downloadImages){
      const blob = await resp.blob();
      const objectUrl = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = objectUrl;
      a.download = `${getLastPartOfUrl(url)}.zip` || "markdd.zip";
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(objectUrl);
      toast({
        title: t("downloadStartedTitle"),
        description: t("downloadStartedDesc"),
      })
      track("Downloaded Markdown", {withImages: true})
    }
    saveSettingsToLocalStorage()
    setIsLoading(false)
  }
  return (
    (<main className="w-full min-h-[100vh] py-6 space-y-6 flex justify-center items-center relative">
      <Toaster />
      <div className="absolute right-4 top-4 z-10 flex items-center gap-2">
        <button
          type="button"
          onClick={() => setSettingsOpen(true)}
          title={t("settingsTitle")}
          aria-label={t("settingsTitle")}
          className={
            "flex h-8 w-8 items-center justify-center rounded-full border border-gray-200 bg-white/80 shadow-sm backdrop-blur transition-colors hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-900/70 dark:hover:bg-gray-800 " +
            (hasKey ? "text-orange-500" : "text-gray-500")
          }>
          <SettingsIcon className="h-4 w-4" />
        </button>
        <LanguageSwitch />
      </div>
      <SettingsDialog open={settingsOpen} onClose={() => setSettingsOpen(false)} />
      <div className="container flex flex-col items-center justify-center">
        <div className="space-y-2 text-center mb-10">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl">📥<br/>Markdown<b>Down</b></h1>
          <p
            className="max-w-[600px] text-gray-500 md:text-xl/relaxed dark:text-gray-400">
            {t("subtitle")}<br/> {t("subtitle2")}
          </p>
        </div>
        <div className="w-full max-w-sm space-y-2">
          <div className="flex w-full max-w-sm items-center space-x-2 mb-10">
            <Input value={url} type="text" placeholder={t("urlPlaceholder")} onChange={val=>setUrl(val.target.value)} onKeyDown={(e)=>{
              if (e.key === "Enter"){
                submit()
              }
            }} />
            <Button disabled={isLoading} type="submit" onClick={submit}>
              {isLoading ? t("converting") : t("convert")}
            </Button>
          </div>
          
          <div className="space-y-2 flex flex-col gap-4">
            <Card>
              <CardHeader>
                <CardTitle>{t("options")}</CardTitle>
              </CardHeader>
              <CardContent>
              <div className="flex items-center space-x-2">
              <Checkbox id="remove-noncontent" checked={removeNonContent} onClick={t=>setRemoveNonContent(!removeNonContent)} />
              <label className="text-sm leading-none" htmlFor="remove-noncontent">
                {t("removeNonContent")}
                <HelpTooltip>
                  {t("removeNonContentHelp")}
                </HelpTooltip>
              </label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox id="remove-images" checked={downloadImages} onClick={t=>setDownloadImages(!downloadImages)} />
              <label className="text-sm leading-none" htmlFor="remove-images">
                {t("downloadImages")}
                <HelpTooltip>
                  {t("downloadImagesHelp")}
                </HelpTooltip>
              </label>
            </div>
            <div className="flex items-center space-x-2">
            <Checkbox id="apply-gpt" checked={gptEnabled} onClick={t=>{
              const newValue = !gptEnabled;
              if (!newValue){
                setApplyGpt("")
              }
              setGptEnabled(newValue);
              }} />
              <Label className="text-sm leading-none ml-2" htmlFor="apply-gpt">
                {t("applyGpt")}
                <HelpTooltip>
                  {t("applyGptHelp")}
                </HelpTooltip>
              </Label>
            </div>
              </CardContent>
            </Card>
            
            {downloadImages && (
              <Card>
              <CardHeader>
                <CardTitle>{t("imageOptions")}</CardTitle>
              </CardHeader>
              <CardContent>
              <>
              <div className="space-y-2">
              <Label className="text-sm leading-none" htmlFor="images-folder">
                {t("overrideImagesFolder")}
                <HelpTooltip>
                  {t("overrideImagesFolderHelp")}
                </HelpTooltip>
              </Label>
              <Input id="images-folder" placeholder={t("enterFolderName")} type="text" value={imagesDir} onChange={val=>{
                setImagesDir(val.target.value)
              }} />
              
            </div>
            <div className="space-y-2">
              <Label className="text-sm leading-none" htmlFor="images-basepath">
                {t("overrideBasePath")}
                <HelpTooltip>
                  {t("overrideBasePathHelp")}
                </HelpTooltip>
              </Label>
              <Input id="images-basepath" placeholder={`./${imagesDir}`} type="text" value={imagesBasePathOverride} onChange={val=>{
                SetImagesBasePathOverride(val.target.value)
              }} />
              </div>
              </>
              </CardContent>
            </Card>
            )}
 {gptEnabled && <Card>
              <CardHeader>
                <CardTitle>{t("gptOptions")}</CardTitle>
              </CardHeader>
              <CardContent>
            <div className="space-y-2">
            
              
                <div className="flex items-center space-x-2">
                <Checkbox id="big-model" checked={bigModel} onClick={t=>setBigModel(!bigModel)} />
                <label className="text-sm leading-none" htmlFor="big-model">
                  {t("useGpt4")}
                </label>
              </div>
              <Textarea id="apply-gpt-txt" 
              className="min-h-[20rem]"
              placeholder={t("gptPlaceholder")} value={applyGpt} onChange={val=>{ 
                setApplyGpt(val.target.value)
              }} />
            </div>
            </CardContent>
            </Card>}
            
          </div>
          
        </div>
        <footer className="mt-10 text-xs text-gray-500 dark:text-gray-400">
          <p>
          © {new Date().getFullYear()}&nbsp;
            <a className="underline" href="https://twitter.com/_asadmemon" target="_blank" rel="noopener noreferrer">
              Asad Memon
            </a>
          </p>
        </footer>
      </div>
      
    </main>)
  );
}
